import React, { useState, useEffect } from 'react';
import { JobPosting, CandidatePrepKit, MockAnswerFeedback } from '../types';
import { fetchRolePrepKit, submitPracticeAnswer } from '../services/prepService';
import { 
  Sparkles, 
  BookOpen, 
  HelpCircle, 
  ShieldCheck, 
  CheckCircle2, 
  XCircle, 
  Download, 
  ArrowRight, 
  Send, 
  RefreshCw, 
  Award, 
  Lightbulb, 
  Bot, 
  Briefcase, 
  HeartHandshake, 
  Building2,
  FileCheck
} from 'lucide-react';

interface CandidateResourceCenterProps {
  jobs: JobPosting[];
  onNavigateToScreening?: () => void;
  onNavigateToJobs?: () => void;
  initialJobId?: string;
}

export const CandidateResourceCenter: React.FC<CandidateResourceCenterProps> = ({
  jobs,
  onNavigateToScreening,
  onNavigateToJobs,
  initialJobId
}) => {
  const [selectedJobId, setSelectedJobId] = useState<string>(initialJobId || jobs[0]?.id || '');
  const [prepKit, setPrepKit] = useState<CandidatePrepKit | null>(null);
  const [isLoadingKit, setIsLoadingKit] = useState(false);
  const [activeSection, setActiveSection] = useState<'focus' | 'questions' | 'ethics' | 'practice'>('focus');

  // Practice sandbox state
  const [selectedPracticeQuestion, setSelectedPracticeQuestion] = useState<string>('');
  const [practiceAnswer, setPracticeAnswer] = useState<string>('');
  const [isSubmittingPractice, setIsSubmittingPractice] = useState<boolean>(false);
  const [practiceFeedback, setPracticeFeedback] = useState<MockAnswerFeedback | null>(null);

  const selectedJob = jobs.find((j) => j.id === selectedJobId) || jobs[0];

  useEffect(() => {
    if (!selectedJob) return;

    let isMounted = true;
    async function loadKit() {
      setIsLoadingKit(true);
      try {
        const kit = await fetchRolePrepKit(selectedJob.title, selectedJob.department, selectedJob.techStack);
        if (isMounted) {
          setPrepKit(kit);
          if (kit.sampleQuestions.length > 0) {
            setSelectedPracticeQuestion(kit.sampleQuestions[0].question);
          }
          setPracticeFeedback(null);
          setPracticeAnswer('');
        }
      } catch (err) {
        console.warn('Could not load prep kit:', err);
      } finally {
        if (isMounted) setIsLoadingKit(false);
      }
    }

    loadKit();
    return () => {
      isMounted = false;
    };
  }, [selectedJobId]);

  const handlePracticeSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!practiceAnswer.trim() || !selectedPracticeQuestion) return;

    setIsSubmittingPractice(true);
    try {
      const feedback = await submitPracticeAnswer(selectedJob.title, selectedPracticeQuestion, practiceAnswer);
      setPracticeFeedback(feedback);
    } catch (err) {
      console.warn('Practice submission error:', err);
    } finally {
      setIsSubmittingPractice(false);
    }
  };

  const handleDownloadPrepGuide = () => {
    if (!prepKit) return;

    const content = `# AIREV Emerging Center — Candidate Interview Preparation Kit
Role: ${selectedJob.title}
Department: ${selectedJob.department}
Location: ${selectedJob.location}
Salary Band: ${selectedJob.salaryRange}

## Role Overview
${prepKit.roleOverview}

## Key Technical Focus Areas
${prepKit.technicalFocusAreas.map((f, i) => `${i + 1}. [${f.importance}] ${f.topic}\n   Tip: ${f.tips}`).join('\n\n')}

## High-Frequency Interview Questions & Ideal Blueprints
${prepKit.sampleQuestions.map((q, i) => `Q${i + 1}: ${q.question} (${q.category})\nWhat Evaluators Look For: ${q.whatEvaluatorsLookFor}\nIdeal Answer Blueprint: ${q.idealAnswerBlueprint}`).join('\n\n')}

## AIREV Corporate Ethics & Workplace Culture
${prepKit.corporateEthicsAndCultureTips.map((tip, i) => `• ${tip}`).join('\n')}

## Interview Dos & Don'ts
DOs:
${prepKit.dosAndDonts.dos.map((d) => `  ✓ ${d}`).join('\n')}

DON'Ts:
${prepKit.dosAndDonts.donts.map((d) => `  ✗ ${d}`).join('\n')}

## Recommended Study Topics
${prepKit.recommendedStudyTopics.map((t) => `• ${t.title}: ${t.description}`).join('\n')}

--
Generated by AIREV Emerging Center Talent Operations, Karachi, Pakistan.
`;

    const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `AIREV_Interview_Prep_${selectedJob.title.replace(/\s+/g, '_')}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-10 pb-20 max-w-6xl mx-auto">
      {/* Header Banner */}
      <section className="relative overflow-hidden rounded-2xl border border-slate-800 bg-gradient-to-b from-slate-900 via-slate-950 to-slate-950 p-6 sm:p-10">
        <div className="relative z-10 space-y-4 max-w-3xl">
          <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-blue-400">
            <Sparkles className="h-4 w-4 text-orange-400" />
            <span>Empowering Candidate Success · AI-Powered Preparation Hub</span>
          </div>

          <h1 className="text-3xl sm:text-4xl font-extrabold tracking-tight text-white">
            Candidate Resource Center
          </h1>

          <p className="text-sm text-slate-300 leading-relaxed font-normal">
            At <strong>AIREV Emerging Center</strong>, we believe interviews should test genuine engineering depth, not trick questions. Explore role-tailored technical focus areas, evaluator rubrics, Pakistani corporate culture expectations, and test your answers in our real-time practice sandbox.
          </p>

          <div className="flex flex-wrap items-center gap-3 pt-2 text-xs text-slate-400">
            <span className="flex items-center gap-1.5 text-emerald-400 font-semibold">
              <CheckCircle2 className="h-4 w-4" />
              <span>Tailored for 100K – 150K PKR Karachi Roles</span>
            </span>
            <span className="text-slate-600">·</span>
            <span className="flex items-center gap-1.5 text-blue-400 font-semibold">
              <Building2 className="h-4 w-4" />
              <span>On-Site Emerging Center Standards</span>
            </span>
          </div>
        </div>
      </section>

      {/* Role Selection Segment */}
      <section className="space-y-3">
        <div className="flex items-center justify-between text-xs">
          <span className="font-bold uppercase tracking-wider text-slate-400">
            Select Your Target Vacancy for Customized Prep:
          </span>
          <span className="text-slate-500 font-mono">
            {jobs.length} On-Site Karachi Openings
          </span>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
          {jobs.map((job) => {
            const isSelected = job.id === selectedJobId;
            return (
              <button
                key={job.id}
                onClick={() => setSelectedJobId(job.id)}
                className={`rounded-xl border p-4 text-left transition-all ${
                  isSelected
                    ? 'border-blue-500 bg-blue-950/40 text-white shadow-md ring-1 ring-blue-500/50'
                    : 'border-slate-800 bg-slate-900/60 text-slate-300 hover:border-slate-700 hover:bg-slate-900'
                }`}
              >
                <div className="text-[10px] font-bold uppercase tracking-wider text-orange-400 mb-1">
                  {job.department.split('&')[0]}
                </div>
                <div className="text-xs sm:text-sm font-bold leading-snug line-clamp-2">
                  {job.title}
                </div>
                <div className="text-[11px] font-semibold text-emerald-400 mt-2">
                  {job.salaryRange}
                </div>
              </button>
            );
          })}
        </div>
      </section>

      {/* Main Prep Kit Section */}
      {isLoadingKit ? (
        <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-12 text-center space-y-3">
          <RefreshCw className="h-8 w-8 animate-spin text-blue-400 mx-auto" />
          <p className="text-sm text-slate-300 font-medium">
            Generating AI Interview Prep Kit for {selectedJob.title}...
          </p>
          <p className="text-xs text-slate-500">
            Calibrating technical competencies, Karachi corporate ethics, and sample blueprints
          </p>
        </div>
      ) : prepKit ? (
        <section className="rounded-2xl border border-slate-800 bg-slate-900/60 overflow-hidden space-y-0">
          {/* Subheader with Action Bar */}
          <div className="p-5 sm:p-6 border-b border-slate-800 bg-slate-950/70 flex flex-col md:flex-row md:items-center justify-between gap-4">
            <div>
              <div className="flex items-center gap-2 text-xs font-semibold text-blue-400">
                <Briefcase className="h-3.5 w-3.5" />
                <span>AIREV Emerging Center · Karachi On-Site</span>
              </div>
              <h2 className="text-xl sm:text-2xl font-bold text-white mt-0.5">
                Interview Prep Kit: {selectedJob.title}
              </h2>
              <p className="text-xs text-slate-400 mt-1 max-w-2xl">
                {prepKit.roleOverview}
              </p>
            </div>

            <div className="flex items-center gap-2.5">
              <button
                onClick={handleDownloadPrepGuide}
                className="inline-flex items-center gap-1.5 rounded-lg border border-slate-700 bg-slate-800 px-3.5 py-2 text-xs font-medium text-slate-200 hover:bg-slate-700 hover:text-white transition-all shadow-sm"
              >
                <Download className="h-3.5 w-3.5 text-emerald-400" />
                <span>Download Kit (.MD)</span>
              </button>

              {onNavigateToScreening && (
                <button
                  onClick={onNavigateToScreening}
                  className="inline-flex items-center gap-1.5 rounded-lg bg-[#2563EB] px-4 py-2 text-xs font-semibold text-white shadow-sm hover:bg-blue-600 transition-all"
                >
                  <Bot className="h-3.5 w-3.5" />
                  <span>Enter AI Screening Room</span>
                  <ArrowRight className="h-3.5 w-3.5" />
                </button>
              )}
            </div>
          </div>

          {/* Section Navigation Tabs */}
          <div className="border-b border-slate-800 bg-slate-950/40 px-6 flex items-center gap-6 overflow-x-auto text-xs font-medium">
            <button
              onClick={() => setActiveSection('focus')}
              className={`py-3.5 transition-colors border-b-2 flex items-center gap-2 whitespace-nowrap ${
                activeSection === 'focus'
                  ? 'border-blue-500 text-white font-bold'
                  : 'border-transparent text-slate-400 hover:text-slate-200'
              }`}
            >
              <Lightbulb className="h-4 w-4 text-orange-400" />
              <span>Core Technical Rubric</span>
            </button>

            <button
              onClick={() => setActiveSection('questions')}
              className={`py-3.5 transition-colors border-b-2 flex items-center gap-2 whitespace-nowrap ${
                activeSection === 'questions'
                  ? 'border-blue-500 text-white font-bold'
                  : 'border-transparent text-slate-400 hover:text-slate-200'
              }`}
            >
              <HelpCircle className="h-4 w-4 text-blue-400" />
              <span>Sample Q&A Blueprints ({prepKit.sampleQuestions.length})</span>
            </button>

            <button
              onClick={() => setActiveSection('ethics')}
              className={`py-3.5 transition-colors border-b-2 flex items-center gap-2 whitespace-nowrap ${
                activeSection === 'ethics'
                  ? 'border-blue-500 text-white font-bold'
                  : 'border-transparent text-slate-400 hover:text-slate-200'
              }`}
            >
              <HeartHandshake className="h-4 w-4 text-emerald-400" />
              <span>Corporate Ethics & Culture Guide</span>
            </button>

            <button
              onClick={() => setActiveSection('practice')}
              className={`py-3.5 transition-colors border-b-2 flex items-center gap-2 whitespace-nowrap ${
                activeSection === 'practice'
                  ? 'border-blue-500 text-white font-bold'
                  : 'border-transparent text-slate-400 hover:text-slate-200'
              }`}
            >
              <Award className="h-4 w-4 text-purple-400" />
              <span>Interactive Mock Practice Sandbox</span>
            </button>
          </div>

          {/* Section 1: Core Technical Focus Areas */}
          {activeSection === 'focus' && (
            <div className="p-6 sm:p-8 space-y-6">
              <div>
                <h3 className="text-base font-bold text-white">What AIREV Assessors Evaluate</h3>
                <p className="text-xs text-slate-400 mt-0.5">
                  Priority topics graded in both autonomous screening and the on-site whiteboard round
                </p>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                {prepKit.technicalFocusAreas.map((f, idx) => (
                  <div key={idx} className="rounded-xl border border-slate-800 bg-slate-950 p-5 space-y-2">
                    <div className="flex items-center justify-between">
                      <span className="text-[10px] font-bold uppercase tracking-wider text-slate-500">
                        Topic {idx + 1}
                      </span>
                      <span className={`text-[10px] font-bold px-2 py-0.5 rounded ${
                        f.importance === 'Critical'
                          ? 'bg-rose-950 text-rose-300 border border-rose-800/60'
                          : 'bg-blue-950 text-blue-300 border border-blue-800/60'
                      }`}>
                        {f.importance} Priority
                      </span>
                    </div>
                    <div className="text-sm font-bold text-white">{f.topic}</div>
                    <p className="text-xs text-slate-300 leading-relaxed pt-1">
                      {f.tips}
                    </p>
                  </div>
                ))}
              </div>

              {/* Recommended Study Topics */}
              <div className="mt-6 rounded-xl border border-slate-800 bg-slate-950 p-5 space-y-3">
                <div className="flex items-center gap-2 text-xs font-bold text-blue-400 uppercase tracking-wider">
                  <BookOpen className="h-4 w-4" />
                  <span>Curated Study Topics & Documentation</span>
                </div>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
                  {prepKit.recommendedStudyTopics.map((st, i) => (
                    <div key={i} className="rounded-lg border border-slate-800/80 bg-slate-900/60 p-3.5">
                      <span className="font-semibold text-white block">{st.title}</span>
                      <span className="text-slate-400 text-[11px] mt-1 block">{st.description}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}

          {/* Section 2: Sample Questions & Blueprints */}
          {activeSection === 'questions' && (
            <div className="p-6 sm:p-8 space-y-6">
              <div>
                <h3 className="text-base font-bold text-white">High-Frequency Screening Questions</h3>
                <p className="text-xs text-slate-400 mt-0.5">
                  Examine the exact structure evaluators use to measure technical rigor and analytical depth
                </p>
              </div>

              <div className="space-y-4">
                {prepKit.sampleQuestions.map((q, idx) => (
                  <div key={idx} className="rounded-xl border border-slate-800 bg-slate-950 p-5 space-y-3">
                    <div className="flex items-center justify-between">
                      <span className="text-xs font-bold text-blue-400 uppercase tracking-wider">
                        Question {idx + 1} · {q.category}
                      </span>
                      <button
                        onClick={() => {
                          setSelectedPracticeQuestion(q.question);
                          setActiveSection('practice');
                        }}
                        className="text-[11px] font-semibold text-orange-400 hover:text-orange-300 underline"
                      >
                        Try Answering in Sandbox →
                      </button>
                    </div>

                    <p className="text-sm font-semibold text-white">
                      "{q.question}"
                    </p>

                    <div className="rounded-lg bg-slate-900/80 p-3 text-xs border border-slate-800/80 space-y-1.5">
                      <div>
                        <strong className="text-slate-400">What Evaluators Look For: </strong>
                        <span className="text-slate-200">{q.whatEvaluatorsLookFor}</span>
                      </div>
                      <div className="pt-1.5 border-t border-slate-800/80">
                        <strong className="text-emerald-400">Ideal Answer Blueprint: </strong>
                        <span className="text-slate-300">{q.idealAnswerBlueprint}</span>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Section 3: AIREV Corporate Ethics & Workplace Culture */}
          {activeSection === 'ethics' && (
            <div className="p-6 sm:p-8 space-y-6">
              <div>
                <h3 className="text-base font-bold text-white">Karachi On-Site Ethics & Culture Guide</h3>
                <p className="text-xs text-slate-400 mt-0.5">
                  How we operate daily at AIREV Emerging Center: standards of integrity, punctuality, and respect
                </p>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="rounded-xl border border-slate-800 bg-slate-950 p-5 space-y-3">
                  <div className="flex items-center gap-2 text-xs font-bold text-emerald-400 uppercase tracking-wider">
                    <ShieldCheck className="h-4 w-4" />
                    <span>Non-Negotiable Ethics & Workplace Conduct</span>
                  </div>
                  <ul className="space-y-2 text-xs text-slate-300">
                    {prepKit.corporateEthicsAndCultureTips.map((tip, i) => (
                      <li key={i} className="flex items-start gap-2">
                        <CheckCircle2 className="h-4 w-4 text-emerald-400 shrink-0 mt-0.5" />
                        <span>{tip}</span>
                      </li>
                    ))}
                  </ul>
                </div>

                <div className="rounded-xl border border-slate-800 bg-slate-950 p-5 space-y-3">
                  <div className="flex items-center gap-2 text-xs font-bold text-blue-400 uppercase tracking-wider">
                    <Building2 className="h-4 w-4" />
                    <span>On-Site Emerging Center Environment</span>
                  </div>
                  <ul className="space-y-2 text-xs text-slate-300">
                    <li className="flex items-start gap-2">
                      <span className="text-blue-400 font-bold">•</span>
                      <span><strong>Core Office Timings:</strong> 9:30 AM to 6:00 PM PKT at Shahrah-e-Faisal / Clifton, Karachi.</span>
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-blue-400 font-bold">•</span>
                      <span><strong>Uninterrupted Workstation:</strong> Dual high-speed fiber lines + 24/7 automatic generator power.</span>
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-blue-400 font-bold">•</span>
                      <span><strong>On-Time 1st of Month Payroll:</strong> Direct bank transfer in the 100k - 150k PKR band.</span>
                    </li>
                  </ul>
                </div>
              </div>

              {/* Dos and Don'ts */}
              <div className="rounded-xl border border-slate-800 bg-slate-950 p-5 space-y-4">
                <h4 className="text-xs font-bold uppercase tracking-wider text-slate-300">
                  Candidate Interview Dos & Don'ts
                </h4>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-xs">
                  <div className="space-y-2">
                    <span className="text-emerald-400 font-bold flex items-center gap-1.5">
                      <CheckCircle2 className="h-4 w-4" />
                      <span>DO:</span>
                    </span>
                    <ul className="space-y-1.5 text-slate-300">
                      {prepKit.dosAndDonts.dos.map((d, i) => (
                        <li key={i} className="flex items-start gap-1.5">
                          <span className="text-emerald-400 font-bold">✓</span>
                          <span>{d}</span>
                        </li>
                      ))}
                    </ul>
                  </div>

                  <div className="space-y-2">
                    <span className="text-rose-400 font-bold flex items-center gap-1.5">
                      <XCircle className="h-4 w-4" />
                      <span>DON'T:</span>
                    </span>
                    <ul className="space-y-1.5 text-slate-300">
                      {prepKit.dosAndDonts.donts.map((d, i) => (
                        <li key={i} className="flex items-start gap-1.5">
                          <span className="text-rose-400 font-bold">✗</span>
                          <span>{d}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* Section 4: Mock Practice Sandbox */}
          {activeSection === 'practice' && (
            <div className="p-6 sm:p-8 space-y-6">
              <div>
                <h3 className="text-base font-bold text-white">Interactive Mock Answer Sandbox</h3>
                <p className="text-xs text-slate-400 mt-0.5">
                  Type a practice answer below to receive instant Gemini AI scoring and actionable critique before your real assessment
                </p>
              </div>

              <form onSubmit={handlePracticeSubmit} className="rounded-xl border border-slate-800 bg-slate-950 p-5 space-y-4">
                <div>
                  <label className="block text-xs font-bold text-slate-400 uppercase tracking-wider mb-1.5">
                    Select Practice Question:
                  </label>
                  <select
                    value={selectedPracticeQuestion}
                    onChange={(e) => setSelectedPracticeQuestion(e.target.value)}
                    className="w-full rounded-lg border border-slate-700 bg-slate-900 p-2 text-xs text-white focus:border-blue-500 focus:outline-none"
                  >
                    {prepKit.sampleQuestions.map((q, i) => (
                      <option key={i} value={q.question}>
                        {q.question}
                      </option>
                    ))}
                  </select>
                </div>

                <div>
                  <label className="block text-xs font-bold text-slate-400 uppercase tracking-wider mb-1.5">
                    Your Mock Answer:
                  </label>
                  <textarea
                    rows={4}
                    required
                    placeholder="Structure your answer with: 1) What was the scale/problem, 2) Which specific tools/technologies you used, 3) What were the measurable results..."
                    value={practiceAnswer}
                    onChange={(e) => setPracticeAnswer(e.target.value)}
                    className="w-full rounded-lg border border-slate-700 bg-slate-900 p-3 text-xs text-slate-100 placeholder-slate-500 focus:border-blue-500 focus:outline-none leading-relaxed"
                  />
                </div>

                <div className="flex items-center justify-between pt-1">
                  <span className="text-[11px] text-slate-500">
                    Pro-tip: Include concrete numbers (e.g. TPS, latency in ms, bounce rate reduction)
                  </span>

                  <button
                    type="submit"
                    disabled={isSubmittingPractice || !practiceAnswer.trim()}
                    className="inline-flex items-center gap-2 rounded-lg bg-[#2563EB] px-5 py-2 text-xs font-semibold text-white shadow-sm hover:bg-blue-600 transition-all disabled:opacity-50"
                  >
                    {isSubmittingPractice ? (
                      <>
                        <RefreshCw className="h-3.5 w-3.5 animate-spin" />
                        <span>Evaluating Mock Answer...</span>
                      </>
                    ) : (
                      <>
                        <Send className="h-3.5 w-3.5" />
                        <span>Get AI Readiness Feedback</span>
                      </>
                    )}
                  </button>
                </div>
              </form>

              {/* Practice Feedback Card */}
              {practiceFeedback && (
                <div className="rounded-xl border border-blue-900/80 bg-blue-950/20 p-5 space-y-4 animate-in fade-in duration-300">
                  <div className="flex items-center justify-between border-b border-blue-900/50 pb-3">
                    <div className="flex items-center gap-2">
                      <Award className="h-5 w-5 text-orange-400" />
                      <div>
                        <div className="text-xs font-bold uppercase tracking-wider text-blue-300">
                          AI Mock Answer Evaluation
                        </div>
                        <div className="text-sm font-bold text-white mt-0.5">
                          Readiness: {practiceFeedback.readinessVerdict}
                        </div>
                      </div>
                    </div>

                    <div className="flex items-center gap-1.5 font-bold text-lg text-emerald-400">
                      <span>{practiceFeedback.score}</span>
                      <span className="text-xs text-slate-400 font-normal">/ 100</span>
                    </div>
                  </div>

                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
                    <div className="rounded-lg bg-slate-900/80 p-3 border border-emerald-900/40 space-y-1">
                      <span className="font-semibold text-emerald-400 block">Strong Points:</span>
                      <ul className="space-y-1 text-slate-300">
                        {practiceFeedback.strengths.map((s, i) => (
                          <li key={i} className="flex items-start gap-1.5">
                            <span className="text-emerald-400 font-bold">•</span>
                            <span>{s}</span>
                          </li>
                        ))}
                      </ul>
                    </div>

                    <div className="rounded-lg bg-slate-900/80 p-3 border border-orange-900/40 space-y-1">
                      <span className="font-semibold text-orange-400 block">Areas to Polish:</span>
                      <ul className="space-y-1 text-slate-300">
                        {practiceFeedback.improvements.map((imp, i) => (
                          <li key={i} className="flex items-start gap-1.5">
                            <span className="text-orange-400 font-bold">•</span>
                            <span>{imp}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  </div>

                  {practiceFeedback.revisedExampleSnippet && (
                    <div className="rounded-lg bg-slate-900 p-3.5 border border-slate-800 text-xs">
                      <span className="font-semibold text-blue-300 block mb-1">
                        Polished Phrasing Recommendation:
                      </span>
                      <p className="text-slate-300 italic font-mono text-[11px] leading-relaxed">
                        "{practiceFeedback.revisedExampleSnippet}"
                      </p>
                    </div>
                  )}
                </div>
              )}
            </div>
          )}
        </section>
      ) : null}
    </div>
  );
};
